[package]
name = "hermod"
version = "0.1.0"
authors = ["dat14mak <dat14mak@student.lu.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snow = "0.6.2"
